# POST http://localhost:4000/posts
# Content-Type: application/json

# {
#     "penulis": "owlxx",
#     "img": "python.jpg",
#     "kategori": "python",
#     "judul": "belajar fundamental python",
#     "content": "lorem ipsumm daily hard works"
# }

GET http://localhost:4000/posts