# ---------- AUTH -----------
GET http://localhost:4000/api/users
# auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im93bHh4QGdtYWlsLmNvbSIsImlhdCI6MTYyOTk0NjI3OCwiZXhwIjoxNjI5OTQ2ODc4fQ._ptrJdeO39yi84jwoOa2A-ua3GZIS_0KsUbe1OS12hw

# POST http://localhost:4000/signup
# Content-Type: application/json

# {
#     "name": "wancode",
#     "email": "wancode.msg@gmail.com",
#     "password": "wancode123"
# }

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjVmNWJiMTQ5MGNkMWM3Y2JhNjAwZiIsImlhdCI6MTY0NjY1NTAxMywiZXhwIjoxNjQ2NzQxNDEzfQ.tN8k8jmuXRgUWyi2_9mrOxA3I2Rc58SMAKn76R0wRM0

# POST http://localhost:4000/signin
# Content-Type: application/json

# {
#     "email": "wancode.msg@gmail.com",
#     "password": "wancode123"
# }

# DELETE http://localhost:4000/user/delete/610e174acc62717d51db57f7
# auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im93bHh4QGdtYWlsLmNvbSIsImlhdCI6MTYyOTg2NjA0OCwiZXhwIjoxNjI5ODczMjQ4fQ.kTB6kDKG0mrMiGhrwSA5Xbuh8IY_lkp0W9SdzFRb59o

# ---------- AUTH -----------

# ---------- POST -----------

# GET http://localhost:4000/posts
# auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsd2FuQGdtYWlsLmNvbSIsImlhdCI6MTYyODgxMzk4MiwiZXhwIjoxNjI4ODE3NTgyfQ.meeWeNE7yBxuK1bu8SQpb3guInNZ7oCjq9CLgYxQ08E

# POST http://localhost:4000/posts
# Content-Type: application/json

# {
#     "penulis": "alwan",
#     "img": "Aos.png",
#     "kategori": "Aos Js",
#     "judul": "Fundamental Aos Js ",
#     "content": "Halo semuanya kali ini saya akan membagikan belajar fundamental Aos Js"
# }

# PATCH http://localhost:4000/posts/60ebc99cff7a49624f2725f4
# Content-Type: application/json

# {
#     "penulis": "void",
#     "img": "Laravel.png",
#     "kategori": "Laravel",
#     "judul": "Fundamental Laravel 8",
#     "content": "Halo semuanya kali ini saya akan membagikan belajar fundamental react hook"
# }

# DELETE http://localhost:4000/post/6102512d0d958d244a2ac3ee

# ---------- POST -----------

# ACTIVATION
# POST http://localhost:4000/activation
# Content-Type: application/json

# {
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmI5ZDc4ZjNhMGU5NWRiMzlmYTYyOSIsImlhdCI6MTY1MTIxOTgzMywiZXhwIjoxNjUxMzA2MjMzfQ.FVwuGUM8YFZvLFlubSFyXrLwbnze0DT4idXIZd0dXAs"
# }